{application,pavlov,
             [{registered,[]},
              {description,"Pavlov is a BDD library for your Elixir projects, allowing you to write\nexpressive unit tests that tell the story of how your application behaves.\nThe syntax tries to follow RSpec's wherever possible.\n"},
              {vsn,"0.2.3"},
              {modules,['Elixir.Pavlov','Elixir.Pavlov.Callbacks',
                        'Elixir.Pavlov.Case','Elixir.Pavlov.Matchers',
                        'Elixir.Pavlov.Matchers.Messages',
                        'Elixir.Pavlov.Mocks','Elixir.Pavlov.Mocks.Matchers',
                        'Elixir.Pavlov.Mocks.Matchers.Messages',
                        'Elixir.Pavlov.Syntax.Expect',
                        'Elixir.Pavlov.Syntax.Sugar',
                        'Elixir.Pavlov.Utils.Memoize',
                        'Elixir.Pavlov.Utils.Memoize.ResultTable']},
              {applications,[kernel,stdlib,elixir,logger]}]}.